######################
# get users
GET http://127.0.0.1:5000/users


######################
POST http://127.0.0.1:5000/add-user
Content-Type: application/json

{
    "name" : "Mark Mende"
}
######################
######################
######################
######################